//
// Created by annika on 22.04.20.
//

#ifndef ELASTICNODEMIDDLEWARE_CONFIGURATION_H
#define ELASTICNODEMIDDLEWARE_CONFIGURATION_H

void configurationUartFlash(void);

#endif //ELASTICNODEMIDDLEWARE_CONFIGURATION_H
