//
// Created by annika on 28.02.20.
//

#ifndef ELASTICNODEMIDDLEWARE_MEMORYMANAGEMENTDEFINTIONS_H
#define ELASTICNODEMIDDLEWARE_MEMORYMANAGEMENTDEFINTIONS_H

#define TRACING 0
#define REFERENCE_COUNTING 1
#define HARDCODED 2
#define GARBAGE_COLLECTION_TYPE REFERENCE_COUNTING

#define MM_MARK 0
#define MM_FREED 1

#endif //ELASTICNODEMIDDLEWARE_MEMORYMANAGEMENTDEFINTIONS_H
