//
// Created by annika on 28.10.19.
//

#ifndef ELASTICNODEMIDDLEWARE_CONFIGURATION_FLASH_H
#define ELASTICNODEMIDDLEWARE_CONFIGURATION_FLASH_H

void configuration_flash_Flash();

#endif //ELASTICNODEMIDDLEWARE_CONFIGURATION_FLASH_H
