//
// Created by annika on 26.09.19.
//

#ifndef ELASTICNODEMIDDLEWARE_ELASTICNODEMIDDLEWARE_INTERNAL_H
#define ELASTICNODEMIDDLEWARE_ELASTICNODEMIDDLEWARE_INTERNAL_H

#include <stdint.h>

void elasticnode_fpgaPowerOn_internal();

#endif //ELASTICNODEMIDDLEWARE_ELASTICNODEMIDDLEWARE_INTERNAL_H
