//
// Created by annika on 17.09.19.
//


#ifndef ELASTICNODEMIDDLEWARE_FPGAPINS_H
#define ELASTICNODEMIDDLEWARE_FPGAPINS_H

#ifdef TEST
#warning bal
#else
#include <avr/io.h>

#define DDR_FPGA_PROGRAM_B &DDRF
#define PORT_FPGA_PROGRAM_B &PORTF
#define P_FPGA_PROGRAM_B PF2

#define FPGA_POWER_CONTROL_MULTI 1

#define DDR_FPGA_POWER_SRAM &DDRE
#define PORT_FPGA_POWER_SRAM &PORTE
#define P_FPGA_POWER_SRAM PE5
#define DDR_FPGA_POWER_AUX &DDRE
#define PORT_FPGA_POWER_AUX &PORTE
#define P_FPGA_POWER_AUX PE4
#define DDR_FPGA_POWER_IO &DDRE
#define PORT_FPGA_POWER_IO &PORTE
#define P_FPGA_POWER_IO PE7
#define DDR_FPGA_POWER_INT &DDRB
#define PORT_FPGA_POWER_INT &PORTB
#define P_FPGA_POWER_INT PB0
#endif

#endif //ELASTICNODEMIDDLEWARE_FPGAPINS_H
