#ifndef PERIPHERALS_H
#define PERIPHERALS_H

#define USE_LUFA 1

#define DDR_WIRELESS_CS DDRE
#define P_WIRELESS_CS PE6
#define PORT_WIRELESS_CS PORTE

#define DDR_FLASH_CS DDRB
#define P_FLASH_CS PB4
#define PORT_FLASH_CS PORTB

#endif
